server:
    port: 9002

spring:
    application:
        name: TWEET-SERVICE
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:twitter_microservices}
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
    client:
        serviceURL:
            defaultZone: http://service-registry:8761/eureka