server:
  port: 9090

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1.0/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTH-SERVICE
                fallbackuri: forward:/authServiceFallback
        - id: TWEET-SERVICE
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/api/v1.0/tweets/**
          filters:
            - name: CircuitBreaker
              args:
                name: TWEET-SERVICE
                fallbackuri: forward:/tweetServiceFallback
        - id: REPLY-SERVICE
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/api/v1.0/replies/**
          filters:
            - name: CircuitBreaker
              args:
                name: REPLY-SERVICE
                fallbackuri: forward:/replyServiceFallback


eureka:
  client:
    serviceURL:
      defaultZone: http://service-registry:8761/eureka
